### ISSUE TITLE
Issue accepting input on windows

### ISSUE THREAD

**Issue by julianjurai** [Julian-Jurai/BOIX-Chat#1]
Error w/o Policy
```
PS C:\Users\aaron\Desktop\Let's learn Python> py -3 client.py Aaron ws://boixchat.herokuapp.com
Exception in callback _ProactorReadPipeTransport._loop_reading()
handle: <Handle _ProactorReadPipeTransport._loop_reading()>
Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 445, in recv
    self._register_with_iocp(conn)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 718, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'

```

Error w/ policy change
```
Traceback (most recent call last):
  File "C:\Users\mikha\Desktop\Chat\client.py", line 71, in <module>
    asyncio.get_event_loop().run_until_complete(client.run())
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\mikha\Desktop\Chat\client.py", line 15, in run
    await asyncio.gather(
  File "C:\Users\mikha\Desktop\Chat\client.py", line 45, in listen_for_input
    await loop.connect_read_pipe(lambda: asyncio.StreamReaderProtocol(reader), pipe)
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1556, in connect_read_pipe
    transport = self._make_read_pipe_transport(pipe, protocol, waiter)
  File "C:\Users\mikha\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 482, in _make_read_pipe_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by julianjurai** [comment]
Suggestions:

- https://stackoverflow.com/a/63861479/9209362
- https://www.programcreek.com/python/example/125576/asyncio.WindowsSelectorEventLoopPolicy
- https://bugs.python.org/issue43528
- https://docs.python.org/3/library/asyncio-eventloop.html#id12
- https://docs.python.org/3/library/asyncio-subprocess.html
- https://stackoverflow.com/a/36785819/9209362

**Comment by Julian-Jurai** [comment]
Potential Solutions:

- https://docs.python.org/3/library/asyncio-subprocess.html
